name: Deploy
on:
  push:
    branches:
      - develop 

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install -g @hathora/cli
      - run: >
          hathora-cloud deploy --appId app-122d530a-ab60-4597-95d8-fabeecfe3c1b
          --roomsPerProcess 10 --planName tiny --transportType tls
          --containerPort 4000 --env '[]' --token ${{ secrets.HATHORA_TOKEN }}
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v2
      - run: npm install -g surge
      - run: npm ci
      - run: APP_ID=app-122d530a-ab60-4597-95d8-fabeecfe3c1b npm run build
      - run: cp dist/index.html dist/200.html
      - run: surge dist hathora-topdown-shooter.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
