name: Deploy
on:
  push:
    branches:
      - develop 

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install -g hathora
      - run: hathora cloud deploy --appName hathora-topdown-shooter --token ${{ secrets.HATHORA_TOKEN }}
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v2
      - run: npm install -g surge
      - run: npm ci
      - run: APP_ID=e2d8571eb89af72f2abbe909def5f19bc4dad0cd475cce5f5b6e9018017d1f1c npm run build
      - run: cp dist/index.html dist/200.html
      - run: surge dist hathora-topdown-shooter.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
