name: Deploy
on:
  push:
    branches:
      - jc/gh-action-deploy

jobs:
  deploy-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install -g @hathora/cli
      - run: >
          hathora-cloud deploy --appId app-82d434e1-349f-4f50-82f7-b6bdc092f039 --token ${{ secrets.HATHORA_TOKEN }}
  deploy-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Vercel Action
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: team_GPRvMqc4VnOOHT6FlvlpSHa8
          VERCEL_PROJECT_ID: prj_xBbOOFIr9hMzP60ncqtzeK2waKGM
          WORKING_DIRECTORY: client
          VERCEL_SCOPE: hathora
