name: Deploy
on:
  push:
    branches:
      - develop

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install -g @hathora/cli
      - run: >
          hathora-cloud deploy --appId app-122d530a-ab60-4597-95d8-fabeecfe3c1b
          --roomsPerProcess 1 --planName tiny --transportType tls
          --containerPort 4000 --env '[{"name": "DEVELOPER_TOKEN", "value": "${{
          secrets.HATHORA_TOKEN }}"}]' --token ${{ secrets.HATHORA_TOKEN }}
